#include "biuld.h"
#include "soldier.h"
void Create(Build *b,buildkind kind)
{
    b->kind=kind;
    if(b->kind==residence1)
    {
        b->t=10;
        b->money=30;
        b->supply=0;
        b->startt=0;
        b->sell=40;
        b->pic=load_bitmap("residence1.bmp",NULL);
    }
    else if(b->kind==residence2)
    {
        b->t=60;
        b->money=300;
        b->supply=0;
        b->startt=0;
        b->sell=150;
        b->pic=load_bitmap("residence2.bmp",NULL);
    }
    else if(b->kind==money1)
    {
        b->t=60;
        b->money=540;
        b->startt=0;
        b->supply=-90;
        b->sell=70;
        b->pic=load_bitmap("money1.bmp",NULL);
    }
    else if(b->kind==money2)
    {
        b->t=120;
        b->money=1700;
        b->startt=0;
        b->supply=-280;
        b->sell=230;
        b->pic=load_bitmap("money2.bmp",NULL);
    }
    else if(b->kind==supply1)
    {
        b->t=60;
        b->supply=90;
        b->money=-290;
        b->startt=0;
        b->sell=40;
        b->pic=load_bitmap("supply1.bmp",NULL);
    }
    else if(b->kind==supply2)
    {
        b->t=120;
        b->supply=370;
        b->money=-1100;
        b->startt=0;
        b->sell=140;
        b->pic=load_bitmap("supply2.bmp",NULL);
    }
    else if(b->kind==front1Barrack)
    {
        b->soldier.level=1;
        b->soldier.hp=134;
        b->soldier.attack=12;
        b->soldier.defend=12;
        b->soldier.skill[0].money=-600;
        b->soldier.skill[0].supply=-100;
        b->soldier.skill[0].updef=3;
        b->soldier.skill[0].upatk=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=3;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].atk=b->soldier.defend*6.5;
        b->soldier.skill[1].money=-800;
        b->soldier.skill[1].supply=-200;
        b->soldier.skill[2].upatk=2;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].uphp=0;
        b->soldier.Soldier=load_bitmap("front1.bmp",NULL);
        b->pic=load_bitmap("front1Barrack.bmp",NULL);
    }
    else if(b->kind==front2Barrack)
    {
        b->soldier.level=1;
        b->soldier.hp=337;
        b->soldier.attack=41;
        b->soldier.defend=21;
        b->soldier.skill[0].money=-2000;
        b->soldier.skill[0].supply=-300;
        b->soldier.skill[0].upatk=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[0].upatk=7;
        b->soldier.skill[1].round=4;
        b->soldier.skill[1].atk=(b->soldier.defend+b->soldier.attack)*3;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-2500;
        b->soldier.skill[1].supply=-500;
        b->soldier.skill[2].uphp=85;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].upatk=0;
        b->soldier.Soldier=load_bitmap("front2.bmp",NULL);
        b->pic=load_bitmap("front2Barrack.bmp",NULL);
    }
    else if(b->kind==frontmidBarrack)
    {
        b->soldier.level=1;
        b->soldier.hp=437;
        b->soldier.attack=43;
        b->soldier.defend=32;
        b->soldier.skill[0].money=-2000;
        b->soldier.skill[0].supply=-300;
        b->soldier.skill[0].upatk=7;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=4;
        b->soldier.skill[1].atk=(b->soldier.defend+b->soldier.attack)*3;
        b->soldier.skill[1].money=-2500;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].supply=-500;
        b->soldier.skill[2].uphp=85;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].upatk=0;
        b->soldier.Soldier=load_bitmap("frontmid.bmp",NULL);
        b->pic=load_bitmap("frontmidBarrack.bmp",NULL);
    }
    else if(b->kind==mid1Barrack)
    {
        b->soldier.level=1;
        b->soldier.hp=172;
        b->soldier.attack=24;
        b->soldier.defend=12;
        b->soldier.skill[0].money=-10000;
        b->soldier.skill[0].supply=-5000;
        b->soldier.skill[0].upatk=3;
        b->soldier.skill[0].updef=2;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=3;
        b->soldier.skill[1].atk=b->soldier.defend*7.5;
        //more
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-15000;
        b->soldier.skill[1].supply=-8000;
        b->soldier.skill[2].uphp=18;
        b->soldier.skill[2].updef=2;
        b->soldier.skill[2].upatk=0;
        b->soldier.Soldier=load_bitmap("mid1.bmp",NULL);
        b->pic=load_bitmap("mid1Barrack.bmp",NULL);
    }
    else if(b->kind==mid2Barrack)
    {
        b->soldier.level=1;
        b->soldier.hp=366;
        b->soldier.attack=36;
        b->soldier.defend=27;
        b->soldier.skill[0].money=-30000;
        b->soldier.skill[0].supply=-6000;
        b->soldier.skill[0].upatk=6;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=4;
        b->soldier.skill[1].atk=(b->soldier.attack)*1.2;
        //more
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-35000;
        b->soldier.skill[1].supply=-8000;
        b->soldier.skill[2].uphp=33;
        b->soldier.skill[2].upatk=4;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].uphp=0;
        b->soldier.Soldier=load_bitmap("mid2.bmp",NULL);
        b->pic=load_bitmap("mid2Barrack.bmp",NULL);
    }
    else if(b->kind==midbackBarrack)
    {
        b->soldier.level=1;
        b->soldier.hp=647;
        b->soldier.attack=147;
        b->soldier.defend=37;
        b->soldier.skill[0].money=-40000;
        b->soldier.skill[0].supply=-7000;
        b->soldier.skill[0].upatk=23;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=6;
        b->soldier.skill[1].atk=(b->soldier.defend+b->soldier.attack)*1.6;
        //still one
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-45000;
        b->soldier.skill[1].supply=-8000;
        b->soldier.skill[2].upatk=26;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].uphp=0;
        b->soldier.Soldier=load_bitmap("midback.bmp",NULL);
        b->pic=load_bitmap("midbackBarrack.bmp",NULL);
    }
    else if(b->kind==back1Barrack)
    {
        b->soldier.level=1;
        b->soldier.hp=143;
        b->soldier.attack=20;
        b->soldier.defend=10;
        b->soldier.skill[0].money=-900;
        b->soldier.skill[0].supply=-200;
        b->soldier.skill[0].upatk=3;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=3;
        b->soldier.skill[1].atk=b->soldier.attack*1.8;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-2000;
        b->soldier.skill[1].supply=-200;
        b->soldier.skill[2].uphp=13;
        b->soldier.skill[2].upatk=3;
        b->soldier.skill[2].updef=0;
        b->soldier.Soldier=load_bitmap("back1.bmp",NULL);
        b->pic=load_bitmap("back1Barrack.bmp",NULL);
    }
    else if(b->kind==back2Barrack)
    {
        b->soldier.level=1;
        b->soldier.hp=244;
        b->soldier.attack=49;
        b->soldier.defend=17;
        b->soldier.skill[0].money=-3000;
        b->soldier.skill[0].supply=-500;
        b->soldier.skill[0].upatk=8;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=4;
        b->soldier.skill[1].atk=(b->soldier.attack)*1.2;
        //still more
        b->soldier.skill[1].money=-4000;
        b->soldier.skill[1].supply=-700;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[2].uphp=23;
        b->soldier.skill[2].upatk=6;
        b->soldier.skill[2].updef=0;
        b->soldier.Soldier=load_bitmap("back2.bmp",NULL);
        b->pic=load_bitmap("back2Barrack.bmp",NULL);
    }
    else if(b->kind==frontbackBarrack)
    {
        b->soldier.level=1;
        b->soldier.hp=983;
        b->soldier.attack=92;
        b->soldier.defend=63;
        b->soldier.skill[0].money=-100000;
        b->soldier.skill[0].supply=-20000;
        b->soldier.skill[0].upatk=14;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].uphp=0;
        b->soldier.skill[1].round=4;
        b->soldier.skill[1].atk=(b->soldier.attack)*3;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-110000;
        b->soldier.skill[1].supply=-25000;
        b->soldier.skill[2].uphp=246;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].upatk=0;
        b->soldier.Soldier=load_bitmap("frontback.bmp",NULL);
        b->pic=load_bitmap("frontbackBarrack.bmp",NULL);
    }
    else if(b->kind==allBarrack)
    {
        b->soldier.level=1;
        b->soldier.hp=1091;
        b->soldier.attack=198;
        b->soldier.defend=69;
        b->soldier.skill[0].money=-120000;
        b->soldier.skill[0].supply=-24000;
        b->soldier.skill[0].uphp=273;
        b->soldier.skill[0].updef=0;
        b->soldier.skill[0].upatk=0;
        b->soldier.skill[1].round=7;
        b->soldier.skill[1].upatkinwar=(b->soldier.attack)*2.85;
        b->soldier.skill[1].updef=0;
        b->soldier.skill[1].upatk=0;
        b->soldier.skill[1].uphp=0;
        b->soldier.skill[1].money=-170000;
        b->soldier.skill[1].supply=-33000;
        b->soldier.skill[2].upatk=30;
        b->soldier.skill[2].updef=0;
        b->soldier.skill[2].uphp=0;
        b->soldier.Soldier=load_bitmap("all.bmp",NULL);
        b->pic=load_bitmap("allBarrack.bmp",NULL);
    }
}
